### ISSUE TITLE
List third-party libraries & parsers

### ISSUE THREAD

**Issue by EdOverflow** [securitytxt/securitytxt.org#11]
It would be nice to have a little section on securitytxt.org that lists third-party tools related to security.txt.

See: https://github.com/securitytxt/security-txt/issues/40

**Comment by EdOverflow** [comment]
Done in https://github.com/securitytxt/securitytxt.org/commit/8a440708b564a7efe13bad5b9e580ed175e24e36.

**Comment by joker314** [comment]
I made a browser extension, if it's useful: https://github.com/joker314/securitytxt-extension
