### ISSUE TITLE
Dead link for Chrome-Extension

### ISSUE THREAD

**Issue by J-F-B-M** [securitytxt/securitytxt.org#18]
[https://github.com/securitytxt/Extension](https://github.com/securitytxt/Extension) in **Security.txt projects** is dead and should be relinked, replaced or deleted.

**Comment by EdOverflow** [comment]
Well spotted, @J-F-B-M! Thank you for bringing this to my attention.

**Comment by EdOverflow** [comment]
Fixed: https://github.com/securitytxt/securitytxt.org/commit/7f903ad9de6d543c2458bc92edbdcf12963d4f19.
