### ISSUE TITLE
Allow 'chaining' of directives in the form that generates them

### ISSUE THREAD

**Issue by joker314** [securitytxt/securitytxt.org#27]
We could have a `+` icon next to directives that are chainable (i.e., directives which can appear multiple times in the document). Clicking on this plus icon would lead to a new input box, with the same heading as the one from which it stemmed. 

The new input boxes could have `-` (or `x`) icons to remove them.

**Comment by joker314** [comment]
We could add comments with a similar design too.

**Comment by joker314** [comment]
Playing around, I've come up with some mock-ups using [Bulma](https://bulma.io)'s attributes

Ideally, we'd be able to use its `delete`  button which is just a round button with a cross. However, it's designed as a close button for notifications and doesn't seem to support anything beyond that (i.e., it's hard to vertically align it, etc.).

So here is what I think we could go for instead:

![A rounded red remove button next to the input](https://user-images.githubusercontent.com/18113170/53689909-1fb6c980-3d58-11e9-9d52-632281d31151.png)

I think this could be a little confusing as it might not be clear that "Remove" is a button (rather than a label).

So instead, maybe we could remove the rounded corners and even add a bit of space between it and the input, like so:

!["Remove" button still touches the input, but no longer has rounded corners](https://user-images.githubusercontent.com/18113170/53689930-74f2db00-3d58-11e9-82e6-ecf0dce48c9b.png)

or 

!["Remove" button is square and no longer touches the input](https://user-images.githubusercontent.com/18113170/53689939-c1d6b180-3d58-11e9-83f9-8b7b58d74bbc.png)

**Comment by EdOverflow** [comment]
Nice work, @joker314! From a UX point of view, I would personally suggest we put the "Remove" button to the right of the field. That way the fields align when a user is typing.

In addition, I would definitely stick to the rectangular buttons since that adheres to the current design a bit better.

**Comment by joker314** [comment]
Thanks @EdOverflow, will do!
<hr>
The labels will no longer work, because labels need to match up to exactly one input, and we're going to have a list of inputs.

Instead, we might need to use `<fieldset>`s and `<legend>`s... but Bulma doesn't really support those very well, so we'll need to write the CSS for it ourselves possibly.

**Comment by joker314** [comment]
Using the `<fieldset>` tag, I've managed to get it look (I think) reasonably nice. Here's a picture of what I've got so far (there are some padding issues but I'm sure those can be resolved)

![An image of the "Contact" directive segment of the form, with an updated style](https://user-images.githubusercontent.com/18113170/53696941-96d57780-3dc3-11e9-9cd1-3bd84345a73f.png)
