### ISSUE TITLE
Expires field missing

### ISSUE THREAD

**Issue by Itsredd** [securitytxt/securitytxt.org#52]
The provided Tool is seemingly not up to date.
The ```expires``` field which is introduced in Version 9 from the draft isn't provided.
Futhermore the missing ```expires``` field is marked as required in Version 10.

Also, as a suggestion I'd like to add that a user is informed about the current draft version the Tool supports.

**Comment by EdOverflow** [comment]
Thank you for creating an issue ticket, @Itsredd. We have been in the process of implementing one: https://github.com/securitytxt/securitytxt.org/pull/51. :)

**Comment by Itsredd** [comment]
Thanks for the response :)
Good to hear that this issue is already addressed.
