### ISSUE TITLE
"mailto:" is missing from generated mail Contact lines

### ISSUE THREAD

**Issue by rugk** [securitytxt/securitytxt.org#80]
~~I just dropped you a mail (but cannot find it anymore, so cannot copy it)… (If you still have it, copy it here)~~
Ah, it was the contact formula! If you still have that, feel free to copy it in here.

In any case, the issue is the spec mandates `mailto:` for mails, but your generator generates (thus) "non-compliant" `Contact` lines without that prefix.

**Comment by EdOverflow** [comment]
Should be fixed in https://github.com/securitytxt/securitytxt.org/pull/81. Thank you, @rugk. :)
