### ISSUE TITLE
Improve forms

### ISSUE THREAD

**Issue by e-coders** [securitytxt/securitytxt.org#90]
Hi, I am Aasheesh. I have recently send a contact message, as below screenshot
![image](https://user-images.githubusercontent.com/83082760/206492832-9350b1eb-6077-4886-b5f2-2508a16413ce.png)
I said that I will improve your form. Anyways, here I have came to improve it.

A issue that you are using is, that. you are using Formspree for your forms. I'd like you to use FormSubmit, which is a **totally free**, **unlimited** service for email responses, similiar to Formspree. FormSubmit is **completely customizable**, for example, you can edit the success page, so the user will always be in your website, and won't go to any other.

Similiar to FormSpree, go formsubmit.com and read how you can add your form, also scroll down for cool options.

**Comment by EdOverflow** [comment]
I don't currently see the benefits of switching to a different service considering the Formspree form works for us. Closing this issue ticket for now.

**Comment by e-coders** [comment]
The only special feature I recommend you is a thanks page. Formsubmit works same as formspree, but Formsubmit can also let you open another "Mail sent" or "Thanks" page, not like formspree's.
